### ISSUE TITLE
SS4 update

### ISSUE THREAD

**Issue by groundnation** [unclecheese/silverstripe-event-calendar#146]
Hi there unclecheese

Are there any plans for updating the event module for ss4?

James

**Comment by kigi001** [comment]
Hi unclecheese,

I am also interested to know this.

This is the only module that prevents me from upgrading some of my websites to SS4.

Or could you give me some hints on how to upgrade it myself. 
There is quite a big step between SS3 and SS4. Especially with 4.1 and the different folder structure even compared to 4.0 etc.

Any help is very much appreciated.
Thanks

**Comment by unclecheese** [comment]
Glad to know people are still using this module. I can't see myself ever having the resources to put into upgrading it. I still have several other, more popular modules that need upgrading. This would be near the bottom of the list for me, unfortunately.

Are you familiar with the `silverstripe/upgrader` tool? It's come a long way recently. It certainly wouldn't do all the work for you, but it would certainly get a bulk of it done.

**Comment by gheggie** [comment]
@unclecheese Would it be possible for you to create a branch that we could submit PRs to for an SS4 version of this module? I have an SS4 branch on my own fork, and would like to be able to submit a PR to the main repo. My upgrade is in essentially an "alpha" stage at the moment, but might be useful for others to be able to contribute to.

**Comment by gheggie** [comment]
The [4 branch](https://github.com/unclecheese/silverstripe-event-calendar/tree/4) is the Silverstripe 4 compatible version.
