### ISSUE TITLE
updateCMSFields() called multiple times

### ISSUE THREAD

**Issue by pandauxstudio** [unclecheese/silverstripe-event-calendar#68]
Hi,

This explanation was provided by one of the SS support team members.

DocumentConverterDecorator->updateCMSFields() appears to be called multiple times ... The offending line is here: https://github.com/unclecheese/silverstripe-event-calendar/blob/master/code/Calendar.php#L123.

By default SilverStripe calls updateCMSFields() from within DataObject which allows DataExtensions to hook in and add new fields. The first call takes place in DataObject->getCMSFields(), then the second call is as stated above.

Regards,
Zaid Al-Dabbagh

**Comment by unclecheese** [comment]
Sorted. Thanks, Zaid.

**Comment by pandauxstudio** [comment]
I'm not entirely sure, but I think the same fix may need to be applied https://github.com/unclecheese/silverstripe-event-calendar/blob/master/code/CalendarEvent.php#L116.

**Comment by pandauxstudio** [comment]
Actually I had to apply it to get it to work!
